# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/02_models.ipynb (unless otherwise specified).

__all__ = ['load_learner_and_predict']

# Cell
from fastai.vision.all import *
import json

def load_learner_and_predict(path, image_data, thresh=0.5):
    """Load the learner from `path` and predicts the labels for `image`.

    Returns a JSON string, ideal for http requests."""
    learner = load_learner(path)
    image = PILImage.create(image_data)
    _, _, probs = learner.predict(image)
    preds = list(zip(learner.dls.vocab, [prob.item() for prob in probs]))
    preds = [(lab, prob) for lab, prob in preds if prob >= thresh]
    preds.sort(key=lambda x: x[1], reverse=True)
    return json.dumps(
        {
            "preds": [
                {
                    "label": label,
                    "probability": prob,
                }
                for label, prob in preds
            ]
        }
    )